services:
  redis:
    image: "redis:alpine"
    container_name: "kidan_redis_data"
    ports:
      - "6379:6379"

  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: "kidan_mongo_db"
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: